<?php

namespace Database\Seeders;

use DateTime;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SampleEventsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('events')->insert([
            ["name" => "イベント名001", "detail" => "## イベント詳細001", "category" => "カテゴリー001", "tag" => "タグ001", "participation_condition" => "参加条件001", "external_link" => "https://example.com/001", "date" => "2023/06/15", "deadline_date" => "2023/06/14", "place" => "開催場所001", "number_of_recruits" =>    1, "image_path" => "public/events/dummy01.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名002", "detail" => "## イベント詳細002", "category" => "カテゴリー002", "tag" => "タグ002", "participation_condition" => "参加条件002", "external_link" => "https://example.com/002", "date" => "2023/06/16", "deadline_date" => "2023/06/15", "place" => "開催場所002", "number_of_recruits" =>    2, "product_image" => "public/events/dummy02.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名003", "detail" => "## イベント詳細003", "category" => "カテゴリー003", "tag" => "タグ003", "participation_condition" => "参加条件003", "external_link" => "https://example.com/003", "date" => "2023/06/17", "deadline_date" => "2023/06/16", "place" => "開催場所003", "number_of_recruits" =>    3, "product_image" => "public/events/dummy03.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名004", "detail" => "## イベント詳細004", "category" => "カテゴリー004", "tag" => "タグ004", "participation_condition" => "参加条件004", "external_link" => "https://example.com/004", "date" => "2023/06/18", "deadline_date" => "2023/06/17", "place" => "開催場所004", "number_of_recruits" =>    4, "product_image" => "public/events/dummy04.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名005", "detail" => "## イベント詳細005", "category" => "カテゴリー005", "tag" => "タグ005", "participation_condition" => "参加条件005", "external_link" => "https://example.com/005", "date" => "2023/06/19", "deadline_date" => "2023/06/18", "place" => "開催場所005", "number_of_recruits" =>    5, "product_image" => "public/events/dummy05.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名006", "detail" => "## イベント詳細006", "category" => "カテゴリー006", "tag" => "タグ006", "participation_condition" => "参加条件006", "external_link" => "https://example.com/006", "date" => "2023/06/20", "deadline_date" => "2023/06/19", "place" => "開催場所006", "number_of_recruits" =>    6, "product_image" => "public/events/dummy06.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名007", "detail" => "## イベント詳細007", "category" => "カテゴリー007", "tag" => "タグ007", "participation_condition" => "参加条件007", "external_link" => "https://example.com/007", "date" => "2023/06/21", "deadline_date" => "2023/06/20", "place" => "開催場所007", "number_of_recruits" =>    7, "product_image" => "public/events/dummy07.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名008", "detail" => "## イベント詳細008", "category" => "カテゴリー008", "tag" => "タグ008", "participation_condition" => "参加条件008", "external_link" => "https://example.com/008", "date" => "2023/06/22", "deadline_date" => "2023/06/21", "place" => "開催場所008", "number_of_recruits" =>    8, "product_image" => "public/events/dummy08.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名009", "detail" => "## イベント詳細009", "category" => "カテゴリー009", "tag" => "タグ009", "participation_condition" => "参加条件009", "external_link" => "https://example.com/009", "date" => "2023/06/23", "deadline_date" => "2023/06/22", "place" => "開催場所009", "number_of_recruits" =>    9, "product_image" => "public/events/dummy09.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名010", "detail" => "## イベント詳細010", "category" => "カテゴリー010", "tag" => "タグ010", "participation_condition" => "参加条件010", "external_link" => "https://example.com/010", "date" => "2023/06/24", "deadline_date" => "2023/06/23", "place" => "開催場所010", "number_of_recruits" =>    10, "product_image" => "public/events/dummy10.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名011", "detail" => "## イベント詳細011", "category" => "カテゴリー011", "tag" => "タグ011", "participation_condition" => "参加条件011", "external_link" => "https://example.com/011", "date" => "2023/06/25", "deadline_date" => "2023/06/24", "place" => "開催場所011", "number_of_recruits" =>    1, "product_image" => "public/events/dummy11.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名012", "detail" => "## イベント詳細012", "category" => "カテゴリー012", "tag" => "タグ012", "participation_condition" => "参加条件012", "external_link" => "https://example.com/012", "date" => "2023/06/26", "deadline_date" => "2023/06/25", "place" => "開催場所012", "number_of_recruits" =>    2, "product_image" => "public/events/dummy12.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名013", "detail" => "## イベント詳細013", "category" => "カテゴリー013", "tag" => "タグ013", "participation_condition" => "参加条件013", "external_link" => "https://example.com/013", "date" => "2023/06/27", "deadline_date" => "2023/06/26", "place" => "開催場所013", "number_of_recruits" =>    3, "product_image" => "public/events/dummy13.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名014", "detail" => "## イベント詳細014", "category" => "カテゴリー014", "tag" => "タグ014", "participation_condition" => "参加条件014", "external_link" => "https://example.com/014", "date" => "2023/06/28", "deadline_date" => "2023/06/27", "place" => "開催場所014", "number_of_recruits" =>    4, "product_image" => "public/events/dummy14.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名015", "detail" => "## イベント詳細015", "category" => "カテゴリー015", "tag" => "タグ015", "participation_condition" => "参加条件015", "external_link" => "https://example.com/015", "date" => "2023/06/29", "deadline_date" => "2023/06/28", "place" => "開催場所015", "number_of_recruits" =>    5, "product_image" => "public/events/dummy15.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名016", "detail" => "## イベント詳細016", "category" => "カテゴリー016", "tag" => "タグ016", "participation_condition" => "参加条件016", "external_link" => "https://example.com/016", "date" => "2023/06/30", "deadline_date" => "2023/06/29", "place" => "開催場所016", "number_of_recruits" =>    6, "product_image" => "public/events/dummy16.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名017", "detail" => "## イベント詳細017", "category" => "カテゴリー017", "tag" => "タグ017", "participation_condition" => "参加条件017", "external_link" => "https://example.com/017", "date" => "2023/07/01", "deadline_date" => "2023/06/30", "place" => "開催場所017", "number_of_recruits" =>    7, "product_image" => "public/events/dummy17.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名018", "detail" => "## イベント詳細018", "category" => "カテゴリー018", "tag" => "タグ018", "participation_condition" => "参加条件018", "external_link" => "https://example.com/018", "date" => "2023/07/02", "deadline_date" => "2023/07/01", "place" => "開催場所018", "number_of_recruits" =>    8, "product_image" => "public/events/dummy18.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名019", "detail" => "## イベント詳細019", "category" => "カテゴリー019", "tag" => "タグ019", "participation_condition" => "参加条件019", "external_link" => "https://example.com/019", "date" => "2023/07/03", "deadline_date" => "2023/07/02", "place" => "開催場所019", "number_of_recruits" =>    9, "product_image" => "public/events/dummy19.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名020", "detail" => "## イベント詳細020", "category" => "カテゴリー020", "tag" => "タグ020", "participation_condition" => "参加条件020", "external_link" => "https://example.com/020", "date" => "2023/07/04", "deadline_date" => "2023/07/03", "place" => "開催場所020", "number_of_recruits" =>    10, "product_image" => "public/events/dummy20.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名021", "detail" => "## イベント詳細021", "category" => "カテゴリー021", "tag" => "タグ021", "participation_condition" => "参加条件021", "external_link" => "https://example.com/021", "date" => "2023/07/05", "deadline_date" => "2023/07/04", "place" => "開催場所021", "number_of_recruits" =>    1, "product_image" => "public/events/dummy21.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名022", "detail" => "## イベント詳細022", "category" => "カテゴリー022", "tag" => "タグ022", "participation_condition" => "参加条件022", "external_link" => "https://example.com/022", "date" => "2023/07/06", "deadline_date" => "2023/07/05", "place" => "開催場所022", "number_of_recruits" =>    2, "product_image" => "public/events/dummy22.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名023", "detail" => "## イベント詳細023", "category" => "カテゴリー023", "tag" => "タグ023", "participation_condition" => "参加条件023", "external_link" => "https://example.com/023", "date" => "2023/07/07", "deadline_date" => "2023/07/06", "place" => "開催場所023", "number_of_recruits" =>    3, "product_image" => "public/events/dummy23.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名024", "detail" => "## イベント詳細024", "category" => "カテゴリー024", "tag" => "タグ024", "participation_condition" => "参加条件024", "external_link" => "https://example.com/024", "date" => "2023/07/08", "deadline_date" => "2023/07/07", "place" => "開催場所024", "number_of_recruits" =>    4, "product_image" => "public/events/dummy24.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名025", "detail" => "## イベント詳細025", "category" => "カテゴリー025", "tag" => "タグ025", "participation_condition" => "参加条件025", "external_link" => "https://example.com/025", "date" => "2023/07/09", "deadline_date" => "2023/07/08", "place" => "開催場所025", "number_of_recruits" =>    5, "product_image" => "public/events/dummy25.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名026", "detail" => "## イベント詳細026", "category" => "カテゴリー026", "tag" => "タグ026", "participation_condition" => "参加条件026", "external_link" => "https://example.com/026", "date" => "2023/07/10", "deadline_date" => "2023/07/09", "place" => "開催場所026", "number_of_recruits" =>    6, "product_image" => "public/events/dummy26.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名027", "detail" => "## イベント詳細027", "category" => "カテゴリー027", "tag" => "タグ027", "participation_condition" => "参加条件027", "external_link" => "https://example.com/027", "date" => "2023/07/11", "deadline_date" => "2023/07/10", "place" => "開催場所027", "number_of_recruits" =>    7, "product_image" => "public/events/dummy27.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名028", "detail" => "## イベント詳細028", "category" => "カテゴリー028", "tag" => "タグ028", "participation_condition" => "参加条件028", "external_link" => "https://example.com/028", "date" => "2023/07/12", "deadline_date" => "2023/07/11", "place" => "開催場所028", "number_of_recruits" =>    8, "product_image" => "public/events/dummy28.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名029", "detail" => "## イベント詳細029", "category" => "カテゴリー029", "tag" => "タグ029", "participation_condition" => "参加条件029", "external_link" => "https://example.com/029", "date" => "2023/07/13", "deadline_date" => "2023/07/12", "place" => "開催場所029", "number_of_recruits" =>    9, "product_image" => "public/events/dummy29.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名030", "detail" => "## イベント詳細030", "category" => "カテゴリー030", "tag" => "タグ030", "participation_condition" => "参加条件030", "external_link" => "https://example.com/030", "date" => "2023/07/14", "deadline_date" => "2023/07/13", "place" => "開催場所030", "number_of_recruits" =>    10, "product_image" => "public/events/dummy30.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名031", "detail" => "## イベント詳細031", "category" => "カテゴリー031", "tag" => "タグ031", "participation_condition" => "参加条件031", "external_link" => "https://example.com/031", "date" => "2023/07/15", "deadline_date" => "2023/07/14", "place" => "開催場所031", "number_of_recruits" =>    1, "product_image" => "public/events/dummy31.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名032", "detail" => "## イベント詳細032", "category" => "カテゴリー032", "tag" => "タグ032", "participation_condition" => "参加条件032", "external_link" => "https://example.com/032", "date" => "2023/07/16", "deadline_date" => "2023/07/15", "place" => "開催場所032", "number_of_recruits" =>    2, "product_image" => "public/events/dummy32.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名033", "detail" => "## イベント詳細033", "category" => "カテゴリー033", "tag" => "タグ033", "participation_condition" => "参加条件033", "external_link" => "https://example.com/033", "date" => "2023/07/17", "deadline_date" => "2023/07/16", "place" => "開催場所033", "number_of_recruits" =>    3, "product_image" => "public/events/dummy33.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名034", "detail" => "## イベント詳細034", "category" => "カテゴリー034", "tag" => "タグ034", "participation_condition" => "参加条件034", "external_link" => "https://example.com/034", "date" => "2023/07/18", "deadline_date" => "2023/07/17", "place" => "開催場所034", "number_of_recruits" =>    4, "product_image" => "public/events/dummy34.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名035", "detail" => "## イベント詳細035", "category" => "カテゴリー035", "tag" => "タグ035", "participation_condition" => "参加条件035", "external_link" => "https://example.com/035", "date" => "2023/07/19", "deadline_date" => "2023/07/18", "place" => "開催場所035", "number_of_recruits" =>    5, "product_image" => "public/events/dummy35.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名036", "detail" => "## イベント詳細036", "category" => "カテゴリー036", "tag" => "タグ036", "participation_condition" => "参加条件036", "external_link" => "https://example.com/036", "date" => "2023/07/20", "deadline_date" => "2023/07/19", "place" => "開催場所036", "number_of_recruits" =>    6, "product_image" => "public/events/dummy36.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名037", "detail" => "## イベント詳細037", "category" => "カテゴリー037", "tag" => "タグ037", "participation_condition" => "参加条件037", "external_link" => "https://example.com/037", "date" => "2023/07/21", "deadline_date" => "2023/07/20", "place" => "開催場所037", "number_of_recruits" =>    7, "product_image" => "public/events/dummy37.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名038", "detail" => "## イベント詳細038", "category" => "カテゴリー038", "tag" => "タグ038", "participation_condition" => "参加条件038", "external_link" => "https://example.com/038", "date" => "2023/07/22", "deadline_date" => "2023/07/21", "place" => "開催場所038", "number_of_recruits" =>    8, "product_image" => "public/events/dummy38.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名039", "detail" => "## イベント詳細039", "category" => "カテゴリー039", "tag" => "タグ039", "participation_condition" => "参加条件039", "external_link" => "https://example.com/039", "date" => "2023/07/23", "deadline_date" => "2023/07/22", "place" => "開催場所039", "number_of_recruits" =>    9, "product_image" => "public/events/dummy39.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名040", "detail" => "## イベント詳細040", "category" => "カテゴリー040", "tag" => "タグ040", "participation_condition" => "参加条件040", "external_link" => "https://example.com/040", "date" => "2023/07/24", "deadline_date" => "2023/07/23", "place" => "開催場所040", "number_of_recruits" =>    10, "product_image" => "public/events/dummy40.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名041", "detail" => "## イベント詳細041", "category" => "カテゴリー041", "tag" => "タグ041", "participation_condition" => "参加条件041", "external_link" => "https://example.com/041", "date" => "2023/07/25", "deadline_date" => "2023/07/24", "place" => "開催場所041", "number_of_recruits" =>    1, "product_image" => "public/events/dummy41.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名042", "detail" => "## イベント詳細042", "category" => "カテゴリー042", "tag" => "タグ042", "participation_condition" => "参加条件042", "external_link" => "https://example.com/042", "date" => "2023/07/26", "deadline_date" => "2023/07/25", "place" => "開催場所042", "number_of_recruits" =>    2, "product_image" => "public/events/dummy42.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名043", "detail" => "## イベント詳細043", "category" => "カテゴリー043", "tag" => "タグ043", "participation_condition" => "参加条件043", "external_link" => "https://example.com/043", "date" => "2023/07/27", "deadline_date" => "2023/07/26", "place" => "開催場所043", "number_of_recruits" =>    3, "product_image" => "public/events/dummy43.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名044", "detail" => "## イベント詳細044", "category" => "カテゴリー044", "tag" => "タグ044", "participation_condition" => "参加条件044", "external_link" => "https://example.com/044", "date" => "2023/07/28", "deadline_date" => "2023/07/27", "place" => "開催場所044", "number_of_recruits" =>    4, "product_image" => "public/events/dummy44.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名045", "detail" => "## イベント詳細045", "category" => "カテゴリー045", "tag" => "タグ045", "participation_condition" => "参加条件045", "external_link" => "https://example.com/045", "date" => "2023/07/29", "deadline_date" => "2023/07/28", "place" => "開催場所045", "number_of_recruits" =>    5, "product_image" => "public/events/dummy45.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名046", "detail" => "## イベント詳細046", "category" => "カテゴリー046", "tag" => "タグ046", "participation_condition" => "参加条件046", "external_link" => "https://example.com/046", "date" => "2023/07/30", "deadline_date" => "2023/07/29", "place" => "開催場所046", "number_of_recruits" =>    6, "product_image" => "public/events/dummy46.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名047", "detail" => "## イベント詳細047", "category" => "カテゴリー047", "tag" => "タグ047", "participation_condition" => "参加条件047", "external_link" => "https://example.com/047", "date" => "2023/07/31", "deadline_date" => "2023/07/30", "place" => "開催場所047", "number_of_recruits" =>    7, "product_image" => "public/events/dummy47.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名048", "detail" => "## イベント詳細048", "category" => "カテゴリー048", "tag" => "タグ048", "participation_condition" => "参加条件048", "external_link" => "https://example.com/048", "date" => "2023/08/01", "deadline_date" => "2023/07/31", "place" => "開催場所048", "number_of_recruits" =>    8, "product_image" => "public/events/dummy48.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名049", "detail" => "## イベント詳細049", "category" => "カテゴリー049", "tag" => "タグ049", "participation_condition" => "参加条件049", "external_link" => "https://example.com/049", "date" => "2023/08/02", "deadline_date" => "2023/08/01", "place" => "開催場所049", "number_of_recruits" =>    9, "product_image" => "public/events/dummy49.jpg", "organizer_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名050", "detail" => "## イベント詳細050", "category" => "カテゴリー050", "tag" => "タグ050", "participation_condition" => "参加条件050", "external_link" => "https://example.com/050", "date" => "2023/08/03", "deadline_date" => "2023/08/02", "place" => "開催場所050", "number_of_recruits" =>    10, "product_image" => "public/events/dummy50.jpg", "organizer_id" => "2", "created_at" => new DateTime()],
        ]);
    }
}
