<?php

namespace Database\Seeders;

use DateTime;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SampleEventsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('events')->insert([

            ["name" => "イベント名001", "detail" => "イベント詳細001", "category" => "カテゴリー001", "tag" => "タグ001", "conditions_of_participation" => "参加条件001", "estarnal_link" => "https://example.com/001", "datetime" => "2020/01/01 10:00", "place" => "開催場所001", "number_of_people" => 1, "product_image" => "public/events/dummy01.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名002", "detail" => "イベント詳細002", "category" => "カテゴリー002", "tag" => "タグ002", "conditions_of_participation" => "参加条件002", "estarnal_link" => "https://example.com/002", "datetime" => "2020/01/01 10:01", "place" => "開催場所002", "number_of_people" => 2, "product_image" => "public/events/dummy02.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名003", "detail" => "イベント詳細003", "category" => "カテゴリー003", "tag" => "タグ003", "conditions_of_participation" => "参加条件003", "estarnal_link" => "https://example.com/003", "datetime" => "2020/01/01 10:02", "place" => "開催場所003", "number_of_people" => 3, "product_image" => "public/events/dummy03.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名004", "detail" => "イベント詳細004", "category" => "カテゴリー004", "tag" => "タグ004", "conditions_of_participation" => "参加条件004", "estarnal_link" => "https://example.com/004", "datetime" => "2020/01/01 10:03", "place" => "開催場所004", "number_of_people" => 4, "product_image" => "public/events/dummy04.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名005", "detail" => "イベント詳細005", "category" => "カテゴリー005", "tag" => "タグ005", "conditions_of_participation" => "参加条件005", "estarnal_link" => "https://example.com/005", "datetime" => "2020/01/01 10:04", "place" => "開催場所005", "number_of_people" => 5, "product_image" => "public/events/dummy05.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名006", "detail" => "イベント詳細006", "category" => "カテゴリー006", "tag" => "タグ006", "conditions_of_participation" => "参加条件006", "estarnal_link" => "https://example.com/006", "datetime" => "2020/01/01 10:05", "place" => "開催場所006", "number_of_people" => 6, "product_image" => "public/events/dummy06.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名007", "detail" => "イベント詳細007", "category" => "カテゴリー007", "tag" => "タグ007", "conditions_of_participation" => "参加条件007", "estarnal_link" => "https://example.com/007", "datetime" => "2020/01/01 10:06", "place" => "開催場所007", "number_of_people" => 7, "product_image" => "public/events/dummy07.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名008", "detail" => "イベント詳細008", "category" => "カテゴリー008", "tag" => "タグ008", "conditions_of_participation" => "参加条件008", "estarnal_link" => "https://example.com/008", "datetime" => "2020/01/01 10:07", "place" => "開催場所008", "number_of_people" => 8, "product_image" => "public/events/dummy08.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名009", "detail" => "イベント詳細009", "category" => "カテゴリー009", "tag" => "タグ009", "conditions_of_participation" => "参加条件009", "estarnal_link" => "https://example.com/009", "datetime" => "2020/01/01 10:08", "place" => "開催場所009", "number_of_people" => 9, "product_image" => "public/events/dummy09.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名010", "detail" => "イベント詳細010", "category" => "カテゴリー010", "tag" => "タグ010", "conditions_of_participation" => "参加条件010", "estarnal_link" => "https://example.com/010", "datetime" => "2020/01/01 10:09", "place" => "開催場所010", "number_of_people" => 10, "product_image" => "public/events/dummy10.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名011", "detail" => "イベント詳細011", "category" => "カテゴリー011", "tag" => "タグ011", "conditions_of_participation" => "参加条件011", "estarnal_link" => "https://example.com/011", "datetime" => "2020/01/01 10:10", "place" => "開催場所011", "number_of_people" => 11, "product_image" => "public/events/dummy11.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名012", "detail" => "イベント詳細012", "category" => "カテゴリー012", "tag" => "タグ012", "conditions_of_participation" => "参加条件012", "estarnal_link" => "https://example.com/012", "datetime" => "2020/01/01 10:11", "place" => "開催場所012", "number_of_people" => 12, "product_image" => "public/events/dummy12.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名013", "detail" => "イベント詳細013", "category" => "カテゴリー013", "tag" => "タグ013", "conditions_of_participation" => "参加条件013", "estarnal_link" => "https://example.com/013", "datetime" => "2020/01/01 10:12", "place" => "開催場所013", "number_of_people" => 13, "product_image" => "public/events/dummy13.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名014", "detail" => "イベント詳細014", "category" => "カテゴリー014", "tag" => "タグ014", "conditions_of_participation" => "参加条件014", "estarnal_link" => "https://example.com/014", "datetime" => "2020/01/01 10:13", "place" => "開催場所014", "number_of_people" => 14, "product_image" => "public/events/dummy14.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名015", "detail" => "イベント詳細015", "category" => "カテゴリー015", "tag" => "タグ015", "conditions_of_participation" => "参加条件015", "estarnal_link" => "https://example.com/015", "datetime" => "2020/01/01 10:14", "place" => "開催場所015", "number_of_people" => 15, "product_image" => "public/events/dummy15.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名016", "detail" => "イベント詳細016", "category" => "カテゴリー016", "tag" => "タグ016", "conditions_of_participation" => "参加条件016", "estarnal_link" => "https://example.com/016", "datetime" => "2020/01/01 10:15", "place" => "開催場所016", "number_of_people" => 16, "product_image" => "public/events/dummy16.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名017", "detail" => "イベント詳細017", "category" => "カテゴリー017", "tag" => "タグ017", "conditions_of_participation" => "参加条件017", "estarnal_link" => "https://example.com/017", "datetime" => "2020/01/01 10:16", "place" => "開催場所017", "number_of_people" => 17, "product_image" => "public/events/dummy17.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名018", "detail" => "イベント詳細018", "category" => "カテゴリー018", "tag" => "タグ018", "conditions_of_participation" => "参加条件018", "estarnal_link" => "https://example.com/018", "datetime" => "2020/01/01 10:17", "place" => "開催場所018", "number_of_people" => 18, "product_image" => "public/events/dummy18.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名019", "detail" => "イベント詳細019", "category" => "カテゴリー019", "tag" => "タグ019", "conditions_of_participation" => "参加条件019", "estarnal_link" => "https://example.com/019", "datetime" => "2020/01/01 10:18", "place" => "開催場所019", "number_of_people" => 19, "product_image" => "public/events/dummy19.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名020", "detail" => "イベント詳細020", "category" => "カテゴリー020", "tag" => "タグ020", "conditions_of_participation" => "参加条件020", "estarnal_link" => "https://example.com/020", "datetime" => "2020/01/01 10:19", "place" => "開催場所020", "number_of_people" => 20, "product_image" => "public/events/dummy20.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名021", "detail" => "イベント詳細021", "category" => "カテゴリー021", "tag" => "タグ021", "conditions_of_participation" => "参加条件021", "estarnal_link" => "https://example.com/021", "datetime" => "2020/01/01 10:20", "place" => "開催場所021", "number_of_people" => 21, "product_image" => "public/events/dummy21.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名022", "detail" => "イベント詳細022", "category" => "カテゴリー022", "tag" => "タグ022", "conditions_of_participation" => "参加条件022", "estarnal_link" => "https://example.com/022", "datetime" => "2020/01/01 10:21", "place" => "開催場所022", "number_of_people" => 22, "product_image" => "public/events/dummy22.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名023", "detail" => "イベント詳細023", "category" => "カテゴリー023", "tag" => "タグ023", "conditions_of_participation" => "参加条件023", "estarnal_link" => "https://example.com/023", "datetime" => "2020/01/01 10:22", "place" => "開催場所023", "number_of_people" => 23, "product_image" => "public/events/dummy23.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名024", "detail" => "イベント詳細024", "category" => "カテゴリー024", "tag" => "タグ024", "conditions_of_participation" => "参加条件024", "estarnal_link" => "https://example.com/024", "datetime" => "2020/01/01 10:23", "place" => "開催場所024", "number_of_people" => 24, "product_image" => "public/events/dummy24.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名025", "detail" => "イベント詳細025", "category" => "カテゴリー025", "tag" => "タグ025", "conditions_of_participation" => "参加条件025", "estarnal_link" => "https://example.com/025", "datetime" => "2020/01/01 10:24", "place" => "開催場所025", "number_of_people" => 25, "product_image" => "public/events/dummy25.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名026", "detail" => "イベント詳細026", "category" => "カテゴリー026", "tag" => "タグ026", "conditions_of_participation" => "参加条件026", "estarnal_link" => "https://example.com/026", "datetime" => "2020/01/01 10:25", "place" => "開催場所026", "number_of_people" => 26, "product_image" => "public/events/dummy26.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名027", "detail" => "イベント詳細027", "category" => "カテゴリー027", "tag" => "タグ027", "conditions_of_participation" => "参加条件027", "estarnal_link" => "https://example.com/027", "datetime" => "2020/01/01 10:26", "place" => "開催場所027", "number_of_people" => 27, "product_image" => "public/events/dummy27.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名028", "detail" => "イベント詳細028", "category" => "カテゴリー028", "tag" => "タグ028", "conditions_of_participation" => "参加条件028", "estarnal_link" => "https://example.com/028", "datetime" => "2020/01/01 10:27", "place" => "開催場所028", "number_of_people" => 28, "product_image" => "public/events/dummy28.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名029", "detail" => "イベント詳細029", "category" => "カテゴリー029", "tag" => "タグ029", "conditions_of_participation" => "参加条件029", "estarnal_link" => "https://example.com/029", "datetime" => "2020/01/01 10:28", "place" => "開催場所029", "number_of_people" => 29, "product_image" => "public/events/dummy29.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名030", "detail" => "イベント詳細030", "category" => "カテゴリー030", "tag" => "タグ030", "conditions_of_participation" => "参加条件030", "estarnal_link" => "https://example.com/030", "datetime" => "2020/01/01 10:29", "place" => "開催場所030", "number_of_people" => 30, "product_image" => "public/events/dummy30.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名031", "detail" => "イベント詳細031", "category" => "カテゴリー031", "tag" => "タグ031", "conditions_of_participation" => "参加条件031", "estarnal_link" => "https://example.com/031", "datetime" => "2020/01/01 10:30", "place" => "開催場所031", "number_of_people" => 31, "product_image" => "public/events/dummy31.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名032", "detail" => "イベント詳細032", "category" => "カテゴリー032", "tag" => "タグ032", "conditions_of_participation" => "参加条件032", "estarnal_link" => "https://example.com/032", "datetime" => "2020/01/01 10:31", "place" => "開催場所032", "number_of_people" => 32, "product_image" => "public/events/dummy32.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名033", "detail" => "イベント詳細033", "category" => "カテゴリー033", "tag" => "タグ033", "conditions_of_participation" => "参加条件033", "estarnal_link" => "https://example.com/033", "datetime" => "2020/01/01 10:32", "place" => "開催場所033", "number_of_people" => 33, "product_image" => "public/events/dummy33.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名034", "detail" => "イベント詳細034", "category" => "カテゴリー034", "tag" => "タグ034", "conditions_of_participation" => "参加条件034", "estarnal_link" => "https://example.com/034", "datetime" => "2020/01/01 10:33", "place" => "開催場所034", "number_of_people" => 34, "product_image" => "public/events/dummy34.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名035", "detail" => "イベント詳細035", "category" => "カテゴリー035", "tag" => "タグ035", "conditions_of_participation" => "参加条件035", "estarnal_link" => "https://example.com/035", "datetime" => "2020/01/01 10:34", "place" => "開催場所035", "number_of_people" => 35, "product_image" => "public/events/dummy35.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名036", "detail" => "イベント詳細036", "category" => "カテゴリー036", "tag" => "タグ036", "conditions_of_participation" => "参加条件036", "estarnal_link" => "https://example.com/036", "datetime" => "2020/01/01 10:35", "place" => "開催場所036", "number_of_people" => 36, "product_image" => "public/events/dummy36.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名037", "detail" => "イベント詳細037", "category" => "カテゴリー037", "tag" => "タグ037", "conditions_of_participation" => "参加条件037", "estarnal_link" => "https://example.com/037", "datetime" => "2020/01/01 10:36", "place" => "開催場所037", "number_of_people" => 37, "product_image" => "public/events/dummy37.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名038", "detail" => "イベント詳細038", "category" => "カテゴリー038", "tag" => "タグ038", "conditions_of_participation" => "参加条件038", "estarnal_link" => "https://example.com/038", "datetime" => "2020/01/01 10:37", "place" => "開催場所038", "number_of_people" => 38, "product_image" => "public/events/dummy38.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名039", "detail" => "イベント詳細039", "category" => "カテゴリー039", "tag" => "タグ039", "conditions_of_participation" => "参加条件039", "estarnal_link" => "https://example.com/039", "datetime" => "2020/01/01 10:38", "place" => "開催場所039", "number_of_people" => 39, "product_image" => "public/events/dummy39.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名040", "detail" => "イベント詳細040", "category" => "カテゴリー040", "tag" => "タグ040", "conditions_of_participation" => "参加条件040", "estarnal_link" => "https://example.com/040", "datetime" => "2020/01/01 10:39", "place" => "開催場所040", "number_of_people" => 40, "product_image" => "public/events/dummy40.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名041", "detail" => "イベント詳細041", "category" => "カテゴリー041", "tag" => "タグ041", "conditions_of_participation" => "参加条件041", "estarnal_link" => "https://example.com/041", "datetime" => "2020/01/01 10:40", "place" => "開催場所041", "number_of_people" => 41, "product_image" => "public/events/dummy41.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名042", "detail" => "イベント詳細042", "category" => "カテゴリー042", "tag" => "タグ042", "conditions_of_participation" => "参加条件042", "estarnal_link" => "https://example.com/042", "datetime" => "2020/01/01 10:41", "place" => "開催場所042", "number_of_people" => 42, "product_image" => "public/events/dummy42.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名043", "detail" => "イベント詳細043", "category" => "カテゴリー043", "tag" => "タグ043", "conditions_of_participation" => "参加条件043", "estarnal_link" => "https://example.com/043", "datetime" => "2020/01/01 10:42", "place" => "開催場所043", "number_of_people" => 43, "product_image" => "public/events/dummy43.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名044", "detail" => "イベント詳細044", "category" => "カテゴリー044", "tag" => "タグ044", "conditions_of_participation" => "参加条件044", "estarnal_link" => "https://example.com/044", "datetime" => "2020/01/01 10:43", "place" => "開催場所044", "number_of_people" => 44, "product_image" => "public/events/dummy44.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名045", "detail" => "イベント詳細045", "category" => "カテゴリー045", "tag" => "タグ045", "conditions_of_participation" => "参加条件045", "estarnal_link" => "https://example.com/045", "datetime" => "2020/01/01 10:44", "place" => "開催場所045", "number_of_people" => 45, "product_image" => "public/events/dummy45.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名046", "detail" => "イベント詳細046", "category" => "カテゴリー046", "tag" => "タグ046", "conditions_of_participation" => "参加条件046", "estarnal_link" => "https://example.com/046", "datetime" => "2020/01/01 10:45", "place" => "開催場所046", "number_of_people" => 46, "product_image" => "public/events/dummy46.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名047", "detail" => "イベント詳細047", "category" => "カテゴリー047", "tag" => "タグ047", "conditions_of_participation" => "参加条件047", "estarnal_link" => "https://example.com/047", "datetime" => "2020/01/01 10:46", "place" => "開催場所047", "number_of_people" => 47, "product_image" => "public/events/dummy47.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名048", "detail" => "イベント詳細048", "category" => "カテゴリー048", "tag" => "タグ048", "conditions_of_participation" => "参加条件048", "estarnal_link" => "https://example.com/048", "datetime" => "2020/01/01 10:47", "place" => "開催場所048", "number_of_people" => 48, "product_image" => "public/events/dummy48.jpg", "creator_id" => "2", "created_at" => new DateTime()],
            ["name" => "イベント名049", "detail" => "イベント詳細049", "category" => "カテゴリー049", "tag" => "タグ049", "conditions_of_participation" => "参加条件049", "estarnal_link" => "https://example.com/049", "datetime" => "2020/01/01 10:48", "place" => "開催場所049", "number_of_people" => 49, "product_image" => "public/events/dummy49.jpg", "creator_id" => "1", "created_at" => new DateTime()],
            ["name" => "イベント名050", "detail" => "イベント詳細050", "category" => "カテゴリー050", "tag" => "タグ050", "conditions_of_participation" => "参加条件050", "estarnal_link" => "https://example.com/050", "datetime" => "2020/01/01 10:49", "place" => "開催場所050", "number_of_people" => 50, "product_image" => "public/events/dummy50.jpg", "creator_id" => "2", "created_at" => new DateTime()],
        ]);
    }
}
