changelog:
  exclude:
    authors:
      - github-actions
  categories:
    - title: New Features 🎉
      labels:
        - "🌟feature"
    - title: Bug Fix 🕷️
      labels:
        - "🕷️bug"
    - title: Other Changes 🛠
      labels:
        - "*"
